export { default as Favicon } from "/public/images/favicon.png"
export { default as LogoImage } from "/public/images/logo.svg"

export { default as IconAppStore } from "/public/images/app-store.svg"
export { default as IconPlayStore } from "/public/images/play-store.svg"

export { default as PhoneIcon } from "/public/images/phone_icon.svg"
export { default as EnvelopeIcon } from "/public/images/envelope_icon.svg"
export { default as QuoteIcon } from "/public/images/quotes.svg"

export { default as IconBlock } from "/public/images/icon-block.svg"
export { default as IconLayers } from "/public/images/icon-layers.svg"
export { default as IconCreative } from "/public/images/icon-creative.svg"
export { default as IconMapMarker } from "/public/images/icon-map-marker.svg"
export { default as IconPhone } from "/public/images/icon-phone.svg"
export { default as IconEnvelopeFill } from "/public/images/icon-envelope-fill.svg"

// export { default as PhotoMainBannerVector } from "/public/images/main_banner_vector2.svg"
export { default as PhotoMainBanner } from "/public/images/austin-distel-wD1LRb9OeEo-unsplash-1500x750.jpg"
export { default as PhotoHeroBanner } from "/public/images/img_hero-1.png"
export { default as PhotoOurWork } from "/public/images/our_work.jpg"
export { default as PhotoShadow } from "/public/images/shadow.png"
/* export { default as PhotoHelp } from "/public/images/Kia-Car-PNG-HD.png"
export { default as PhotoMainBanner } from "/public/images/pngimg.com---mercedes_PNG80136.png"
export { default as PhotoWork } from "/public/images/Kia-Car-PNG-Photos.png"
export { default as PhotoVector_01 } from "/public/images/vector_01.svg"
export { default as PhotoVector_02 } from "/public/images/vector_02.svg"
export { default as PhotoVector_03 } from "/public/images/vector_03.svg" */
export { default as PhotoWork01 } from "/public/images/work_thumb_01.jpg"
export { default as PhotoWork02 } from "/public/images/work_thumb_02.jpg"
export { default as PhotoWork03 } from "/public/images/work_thumb_03.jpg"
export { default as PhotoWork04 } from "/public/images/work_thumb_04.jpg"
export { default as PhotoWork05 } from "/public/images/work_thumb_05.jpg"
export { default as PhotoWork06 } from "/public/images/work_thumb_06.jpg"
export { default as PhotoBrandCoinbase } from "/public/images/brand_coinbase.svg"
export { default as PhotoBrandJohnDeere } from "/public/images/brand_johnDeere.svg"
export { default as PhotoBrandGrandHyatt } from "/public/images/brand_Grand-Hyatt.svg"
export { default as PhotoBrandBlk_google } from "/public/images/brand_blk_google.svg"
export { default as PhotoBrandVisa } from "/public/images/brand_Visa.svg"
export { default as PhotoBrandZoom } from "/public/images/brand_Zoom.webp"
/* export { default as PhotoShowcase01 } from "/public/images/showcase_01.jpg"
export { default as PhotoShowcase02 } from "/public/images/showcase_02.jpg"
export { default as PhotoShowcase03 } from "/public/images/showcase_03.jpg"
export { default as PhotoShowcase04 } from "/public/images/showcase_04.jpg"
export { default as PhotoShowcase05 } from "/public/images/showcase_05.jpg"
export { default as PhotoShowcase06 } from "/public/images/showcase_06.jpg"
export { default as PhotoShowcase07 } from "/public/images/showcase_07.jpg"
export { default as PhotoShowcase08 } from "/public/images/showcase_08.jpg"
export { default as PhotoShowcase09 } from "/public/images/showcase_09.jpg" */
export { default as PhotoShowcase01 } from "/public/images/showcase/AxiomTechnology.jpg"
export { default as PhotoShowcase02 } from "/public/images/showcase/Blootopia.jpg"
export { default as PhotoShowcase03 } from "/public/images/showcase/BridgeAxis.jpg"
export { default as PhotoShowcase04 } from "/public/images/showcase/Campvine.jpg"
export { default as PhotoShowcase05 } from "/public/images/showcase/Crainly.jpg"
export { default as PhotoShowcase06 } from "/public/images/showcase/CulturalCandy.jpg"
export { default as PhotoShowcase07 } from "/public/images/showcase/ModiglianiAntiquités.jpg"
export { default as PhotoShowcase08 } from "/public/images/showcase/OrowConstruction.jpg"
export { default as PhotoShowcase09 } from "/public/images/showcase/SteveParkRealtor.jpg"
export { default as PhotoShowcase10 } from "/public/images/showcase/TasteHub.jpg"
export { default as PhotoShowcase11 } from "/public/images/showcase/TheEthicalChoice.jpg"
export { default as PhotoShowcase12 } from "/public/images/showcase/TheGenevaCollection.jpg"
export { default as PhotoShowcase13 } from "/public/images/showcase/UCMortgage.jpg"
export { default as PhotoIntro } from "/public/images/home-head.png"
export { default as PhotoReview } from "/public/images/cover@2x.jpg"
export { default as PhotoChoose01 } from "/public/images/choose_01.jpg"
export { default as PhotoChoose02 } from "/public/images/choose_02.png"
export { default as PhotoChoose03 } from "/public/images/choose_03.png"

export { default as PhotoUser_01 } from "/public/images/users/01.jpg"
export { default as PhotoUser_02 } from "/public/images/users/02.jpg"
export { default as PhotoUser_03 } from "/public/images/users/03.jpg"
export { default as PhotoUser_04 } from "/public/images/users/04.jpg"
export { default as PhotoUser_05 } from "/public/images/users/05.jpg"
export { default as PhotoUser_06 } from "/public/images/users/06.jpg"
export { default as PhotoUser_07 } from "/public/images/users/07.jpg"
export { default as PhotoUser_08 } from "/public/images/users/08.jpg"
export { default as PhotoUser_09 } from "/public/images/users/09.jpg"
export { default as PhotoUser_10 } from "/public/images/users/10.jpg"

export { default as PhotoTeam_01 } from "/public/images/team_01.jpg"
export { default as PhotoTeam_02 } from "/public/images/team_02.jpg"
export { default as PhotoTeam_03 } from "/public/images/team_03.jpg"
export { default as PhotoTeam_04 } from "/public/images/team_04.jpg"
export { default as PhotoTeam_05 } from "/public/images/team_05.jpg"
export { default as PhotoTeam_06 } from "/public/images/team_06.jpg"
export { default as PhotoTeam_07 } from "/public/images/team_07.jpg"
export { default as PhotoTeam_08 } from "/public/images/team_08.jpg"

export { default as SocialTwitter } from "/public/images/social-twitter.svg"
export { default as SocialFacebook } from "/public/images/social-facebook.svg"
export { default as SocialLinkedin } from "/public/images/social-linkedin.svg"
export { default as SocialInstagram } from "/public/images/social-instagram.svg"
